#!/usr/bin/env bash
mkdir -p dist
echo "build src/main.ls -> dist/image-type.js ..."
./node_modules/.bin/lsc -cbp src/main.ls > dist/image-type.js
echo "minifying image-type.js ..."
./node_modules/.bin/uglifyjs dist/image-type.js > dist/image-type.min.js
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/image-type/
cp -R dist/* web/static/assets/lib/image-type/
echo "done."

