#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
echo "(function() {" > dist/index.js
./node_modules/.bin/lsc -cbp src/index.ls >> dist/index.js
cat src/colormode.js >> dist/index.js
echo "imgtype.colormode = getColorMode;})();" >> dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js > dist/index.min.js
echo "deploy into local web ..."
rm -rf web/static/assets/lib/imgtype/
mkdir -p web/static/assets/lib/imgtype/dev/
cp -R dist/* web/static/assets/lib/imgtype/dev/
echo "done."

